config/routes.rb
RsvuPortal::Application.routes.draw do
  

  get 'hardware_models/index'

  get 'hardware_models/show'

  get 'hardware_models/create'

  get 'hardware_models/update'

  get 'hardware_types/index'

  get 'hardware_types/show'

  get 'hardware_types/create'

  get 'hardware_types/update'

  get "hardware_reservations/new"
  get "hardware_reservations/index"
  get "hardware_reservations/create"
  get "hardwares/new"
  get "hardwares/index"
  get "search_hardwares", to: "hardwares#search"
  get "search_vms", to: "vms#search"
  
  get "show_reservable", to: "hardwares#show_reservable"
  get "show_reservable", to: "vms#archive"
  

  resources :hardware_models, only: [:show, :edit, :destroy, :update]
	
	resources :software_types
	resources :licenses
	resources :ip_addresses
	resources :archives
	
  resources :hardware_types do
    resources :hardware_models, only: [:new, :create]
  end
    
  resources :hardware_models do 
    resources :hardwares, only: [:new, :create]
  end
  
  resources :group_relations, only: [:create]
  resources :users
  resources :groups do
    get "search_hardwares", to: "hardwares#search"
    resources :group_relations, only: [:create]
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :hardwares
  resources :events
	resources :reservations, only: [:destroy]
	resources :user_messages, only: [:destroy, :edit, :update]
  
  
  
  resources :vmhosts, only: [:index, :show]
  
  resources :vmresourcepools, only: [:show, :edit, :update]
  
  resources :vmhosts do
  	
  	resources :vms
  end
  
  resources :vms do
  	member do
    	get 'archive'
  	end
  	resources :reservations
  	resources :user_messages
  end
  
  resources :hardwares do
  	resources :reservations
  	resources :group_relations, only: [:new, :create]
    resources :devices
  	resources :softwares
  	resources :user_messages
  end
  
  root 'static_pages#home'
  match '/signup',		to: 'users#new',						via: 'get'
  match '/help',			to: 'static_pages#help',	via: 'get'
  match '/about',			to: 'static_pages#about',	via: 'get'
  match '/contact',		to: 'static_pages#contact',	via: 'get'
  match '/signin',		to: 'sessions#new',		via: 'get'
  match '/signout',		to:	'sessions#destroy',		via: 'delete'
  
 
  

end

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						Ошибки
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
	  						<li><%= msg %></li>
	  					<% end %>	
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name,msg| %>
			<div class='alert alert-<%="#{name}" %>'>
				
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
			</div>
		<% end %>
			
	</div>
</div>

app/views/shared/_show_events.html.erb
<% events.each do |event| %>
	<div class="container"> 
  	<div class="row table">
    	<div class="col-lg-3"><%=link_to event.name, event%></div>
    	<div class="col-lg-1">
    		<%= event.reservations.where(reservable_type: "Hardware").count %> / <%= event.reservations.where(reservable_type: "Vm").count %>
     	</div>
    	<% if !event.from_time.nil? %>
    		<div class="col-lg-2"><%=event.from_time.to_date%></div>
    	<% end %>
    	<% if !event.to_time.nil? %>
    		<div class="col-lg-2"><%=event.to_time.to_date%></div>
    	<% end %>
    	<div class="col-lg-1"><%=event.user.firstname%></div>
    	<div class="col-lg-1"><%=event.user.lastname%></div>
    	
    </div>
  </div>
<% end %>

app/views/shared/_show_hardware.html.erb
<td><%= link_to hardware.get_hardware_identificator, hardware%></td>

<% if show_model %>
	<td><%= hardware.hardware_model.name %></td>
<% end %>

<% if show_number %>
	<td><%= hardware.serial_number%></td>
	<td><%= hardware.inv_number%></td>
<% end %>

<td>
	<%= hardware.get_hardware_location %>
	
</td>

app/views/shared/_show_hardwares.html.erb
<table class="table table-striped">	
	<thead>
 		<tr>
 			<th>Идентификатор</th>
 			<% if show_model %> 
 				<th>Модель</th>
 			<% end %>
 			
 			<% if show_number %> 
 				<th>Серийный №</th>
 				<th>Инв. №</th>
 			<% end %>
 			
 			<th>Местоположение</th>
 		</tr>
 	</thead>
	<tbody>
		<% hardwares.each do |h| %>
			<tr>
      	<%= render partial: "shared/show_hardware", locals: {hardware: h, show_model: show_model, show_number: show_number} %>
      </tr>
    <% end %>
	
	</tbody>
</table>

app/views/shared/_show_reservable_hardwares.html.erb

<% reserve.each do |r| %>
	<div class="row table">
		<div class="col-lg-3"><%= link_to r.reservable.get_hardware_full_name, r.reservable %></div>
  	<div class="col-lg-2"><%=r.reservable.identificator%></div>
  	<div class="col-lg-1"><%=r.reservable.hardware_type.name%></div>
  	<div class="col-lg-2"><%=r.reservable.get_hardware_location%></div>
  	<div class="col-lg-1"><%=r.reservable.place%></div>
  	<% if show_user %>
  		<div class="col-lg-2">
  			<%=r.event.user.lastname%> <%=r.event.user.firstname%>
  		</div>
  	<%end%>
  	
  	<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
    	<% if current_user.admin? || current_user?(r.event.user) %>
     		<%=link_to "Освободить", reservation_path(r), method: :delete, data: {confirm: "Вы уверены?"}%>
     	<%end%>
    </div>
  	
	</div>
<% end %>




app/views/shared/_show_reservable_vms.html.erb
<% reserve.each do |r| %>
	<div class="row table">
		<div class="col-lg-2"><%= link_to r.reservable.name, r.reservable %></div>
  	<div class="col-lg-2"><%= render partial: "shared/show_vm_state", locals: {vm: r.reservable} %></div>
  	<div class="col-lg-3"><%=r.reservable.vmresourcepool.name%></div>
  	<div class="col-lg-3"><%=r.reservable.vmresourcepool.vmhost.name%></div>
  	
  	<% if show_user %>
  		<div class="col-lg-2">
  			<%=r.event.user.lastname%> <%=r.event.user.firstname%>
  		</div>
  	<%end%>
  	
  
  	
	</div>
<% end %>

app/views/shared/_show_reservation.html.erb
<%if @vm.reservations.active.count > 0 %>
	<div class="panel panel-warning">
 		<div class="panel-heading">Активные резервирования</div>
  	<div class="panel-body">
   		<ul>
				<div class="row">
				<% @vm.reservations.active.each do |r| %>    				
					<li>
     				<div class="col-lg-3 col-md-4 col-sm-4 col-xs-6"><b><%=r.event.from_time.to_date%> - <%= r.event.to_time.to_date%></b></div>
     				<div class="col-lg-5 col-md-4 col-sm-4 hidden-xs"><%=r.event.name%></div>
     				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-5"><b>Отв.</b>	<%=r.event.user.firstname%> <%=r.event.user.lastname%></div>
     				<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
     					<% if current_user.admin? || current_user?(r.event.user) %>
     						<%=link_to "Удалить", vm_reservation_path(@vm,r), method: :delete, data: {confirm: "Вы уверены?"}%>
     					<%end%>
     				</div>
    			</li>
  			<% end %>
  		</div>
		</ul>
  	</div>
  </div>
<%end%>

app/views/shared/_show_reserves_badge.html.erb
<% if res_subject.use_type and res_subject.use_type == 1 %>
	<a class="btn btn-primary btn-block" data-toggle="collapse" href="#<%=res_subject.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
  	<span class="badge">Служебная</span>
  </a>
<% else %>
	<% if res_subject.reservations.occupied.count > 0 %>
		<a class="btn btn-danger btn-block" data-toggle="collapse" href="#<%=res_subject.id%>" role="button" aria-expanded="false" aria-controls="collapseExample"
			<span class="badge"><%=res_subject.reservations.occupied.last.event.to_time.to_date%></span>
  	</a>
  <% else %>
		<% if res_subject.reservations.active.count > 0 %> <!-- Есть резервы на обоудование -->
  		<% if res_subject.reservations.occupied_nextweek.count > 0 %> <!-- Есть резервы на обоудование на следующей неделе-->
  			<a class="btn btn-warning btn-block" data-toggle="collapse" href="#<%=res_subject.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
    			<span class="badge"><%=res_subject.reservations.occupied_nextweek.first.event.from_time.to_date%></span>
  			</a>
  		<% else %>
  			<div class="btn btn-info btn-block" data-toggle="collapse" href="#<%=res_subject.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
  				<span class="badge"><%=res_subject.reservations.active.first.event.from_time.to_date%></span>
  			</div>
  		<% end %>
  	<% else %>
  		<div class="btn btn-success btn-block">
  			<span class="badge">Свободно</span>
  		</div>
  	<% end %>
  <% end %>
<% end %>

app/views/shared/_show_user_messages.html.erb

<% messages.each do |msg| %>
	<div class="row">
  	<div class="col-lg-12">
  		<%=msg.subject%> 
  	</div>
  	<div class="col-lg-12">
  		<pre><%= msg.body %></pre>
  	</div>
  	<div class="col-lg-5 col-lg-offset-7">
  		<b>Автор:</b><%= msg.user.firstname %> <%= msg.user.lastname %> <b>Создано:</b> <%= msg.created_at %> 
  	</div>
  	<div class="col-lg-4 col-lg-offset-8">
  	<% if (current_user.admin? || msg.user==current_user) %>	
  		<div class="btn-group pull-right">
  			<%= link_to "Редактировать", edit_user_message_path(msg), class: "btn btn-default" %>
  			<%= link_to "Удалить", user_message_path( msg),class: "btn btn-default", method: :delete, data: {confirm: "Вы уверены?"} %>
  		</div>
		<% end %>
	</div>	
	</div>
<% end %>

app/views/shared/_show_vm_datastore.html.erb
<% if ( ds.free_percent < 10) %>
	<span class="label label-danger">
  	<%=Vmdatasource.readable_size(ds.ds_capacity)%> (<%=Vmdatasource.readable_size(ds.ds_freespace)%> <%=ds.free_percent%> %)
  </span>
<% else %>
	<% if ( ds.free_percent < 30) %>
		<span class="label label-warning">
			<%=Vmdatasource.readable_size(ds.ds_capacity)%> (<%=Vmdatasource.readable_size(ds.ds_freespace)%> <%=ds.free_percent%> %)
		</span>
	<% else %>
		<span class="label label-success">
			<%=Vmdatasource.readable_size(ds.ds_capacity)%> (<%=Vmdatasource.readable_size(ds.ds_freespace)%> <%=ds.free_percent%> %)
		</span>
	<% end %>
<% end %>

app/views/shared/_show_vm_ownership.html.erb
<% if vm.valid_to %>
  <% if (vm.valid_to > Time.now.to_date + 1.month ) %>
    <span class="btn btn-success pull-left"><%= vm.get_activity %></span>
  <% else %>
    <% if (vm.valid_to >= Time.now.to_date ) %>
      <span class="btn btn-warning pull-left"><%= vm.get_activity %></span>
    <%else%>
      <span class="btn btn-danger pull-left"><%= vm.get_activity %></span>
    <%end%>
  <%end%>
<% else %>
  <% if vm.user %>
  	<span class="btn btn-primary pull-left"><%= vm.get_activity %></span>
  <% else %>
  	<span class="btn btn-danger pull-left">Неизвестно</span>
  <% end %>
<% end %>



<% if vm.always_on %>
  <span class="btn btn-danger pull-left">!</span>
<% end %>

app/views/shared/_show_vm_state.html.erb
<span class="label state-badge label-<%=Vm.powerstate_to_label(vm.state)%>"><%=Vm.powerstate_to_s(vm.state)%></span>

app/views/shared/_show_vm_valid_to.erb
<%if (_subject.parent_vmresourcepool && _subject.parent_id > 0)%>
		
	<%if (_subject.valid_to)%>
		
		<% if (_subject.valid_to > Time.now.to_date + 1.month ) %>
			<%= link_to _subject.get_activity , vmresourcepool_path(_subject), class: "btn btn-success pull-right"%>
  	<% else %>
  		<% if (_subject.valid_to >= Time.now.to_date ) %>
  			<%= link_to _subject.get_activity , vmresourcepool_path(_subject), class: "btn btn-warning pull-right"%>
  		<%else%>
  			<%= link_to _subject.get_activity , vmresourcepool_path(_subject), class: "btn btn-danger pull-right"%>
  		<%end%>
  	<%end%>

	<%else%>
	
		<%= link_to _subject.get_activity , vmresourcepool_path(_subject), class: "btn btn-danger pull-right"%>
	
	<%end%>
<%end%>