config/routes.rb
RsvuPortal::Application.routes.draw do
  

  get 'hardware_models/index'

  get 'hardware_models/show'

  get 'hardware_models/create'

  get 'hardware_models/update'

  get 'hardware_types/index'

  get 'hardware_types/show'

  get 'hardware_types/create'

  get 'hardware_types/update'

  get "hardware_reservations/new"
  get "hardware_reservations/index"
  get "hardware_reservations/create"
  get "hardwares/new"
  get "hardwares/index"
  get "search_hardwares", to: "hardwares#search"
  get "search_vms", to: "vms#search"
  
  get "show_reservable", to: "hardwares#show_reservable"
  get "show_reservable", to: "vms#archive"
  

  resources :hardware_models, only: [:show, :edit, :destroy, :update]
	
	resources :software_types
	resources :licenses
	resources :ip_addresses
	resources :archives
	
  resources :hardware_types do
    resources :hardware_models, only: [:new, :create]
  end
    
  resources :hardware_models do 
    resources :hardwares, only: [:new, :create]
  end
  
  resources :group_relations, only: [:create]
  resources :users
  resources :groups do
    get "search_hardwares", to: "hardwares#search"
    resources :group_relations, only: [:create]
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :hardwares
  resources :events
	resources :reservations, only: [:destroy]
	resources :user_messages, only: [:destroy, :edit, :update]
  
  
  
  resources :vmhosts, only: [:index, :show]
  
  resources :vmresourcepools, only: [:show, :edit, :update]
  
  resources :vmhosts do
  	
  	resources :vms
  end
  
  resources :vms do
  	member do
    	get 'archive'
  	end
  	resources :reservations
  	resources :user_messages
  end
  
  resources :hardwares do
  	resources :reservations
  	resources :group_relations, only: [:new, :create]
    resources :devices
  	resources :softwares
  	resources :user_messages
  end
  
  root 'static_pages#home'
  match '/signup',		to: 'users#new',						via: 'get'
  match '/help',			to: 'static_pages#help',	via: 'get'
  match '/about',			to: 'static_pages#about',	via: 'get'
  match '/contact',		to: 'static_pages#contact',	via: 'get'
  match '/signin',		to: 'sessions#new',		via: 'get'
  match '/signout',		to:	'sessions#destroy',		via: 'delete'
  
 
  

end

app/models/hardware_model.rb
class HardwareModel < ActiveRecord::Base
  belongs_to :hardware_type
  has_many :hardwares
  
  def get_model_name_with_type
		hardware_type.name + ' '+name
	end
end

app/controllers/hardware_models_controller.rb
class HardwareModelsController < ApplicationController
  before_filter :get_hardware_type, except: [:show, :index, :edit, :update, :create]
  
  def get_hardware_type
		@hardware_type = HardwareType.find(params[:hardware_type_id])		
	end
  
  def create
  		
  	
  	@hardware_model = HardwareModel.new(hardware_model_params)
  	
  	if @hardware_model.save
			redirect_to @hardware_model.hardware_type
		else
		
			render 'new'
		end 
	end
  
  def show
		@hardware_model = HardwareModel.find(params[:id])
		
	end
	
	def edit
		@hardware_model = HardwareModel.find(params[:id])
	end
	
	def update
		
		@hardware_model = HardwareModel.find(params[:id])

		if @hardware_model.update_attributes(hardware_model_params)
			redirect_to @hardware_type
		else
			render 'edit'
		end
	end
	
	def index
		@hardware_models = HardwareModel.all
	end
  
  def new
    @hardware_models = @hardware_type.hardware_models
		@hardware_model =  @hardware_models.build()
    
   
  end
end
private
	def hardware_model_params
	  params.require(:hardware_model).permit(:name,:modelNo,:comment,:sparam1,:sparam2, :sparam3,:iparam1,:iparam2,:iparam3,:hardware_type_id)		
	end

app/helpers/hardware_models_helper.rb
module HardwareModelsHelper
end

app/views/hardware_models/_form.html.erb
<div class="row">
	<%=form_for([@hardware_model]) do |f| %>
		<div class="col-md-6">
			
			<%=f.label :hardware_type_id, "Тип" %>
			<%= f.collection_select(:hardware_type_id, HardwareType.all, :id, :name) %>
			
			<%=f.label :name, "Модель" %>
			<%=f.text_field :name, class: 'form-control' %>
			
			<%=f.label :modelNo, "ID модели" %>
			<%=f.text_field :modelNo, class: 'form-control' %>
			
			<%=f.label :comment,"Коментарий" %>
			<%=f.text_area :comment,  size: "60x12" %>
			
			<% if @hardware_model.hardware_type.sparam1%>
    		<%=f.label :sparam1, @hardware_model.hardware_type.sparam1 %>
  			<%=f.text_field :sparam1, class: 'form-control' %>
  		<%end%>
  			
  		<% if @hardware_model.hardware_type.sparam2%>
    		<%=f.label :sparam2, @hardware_model.hardware_type.sparam2 %>
  			<%=f.text_field :sparam2, class: 'form-control' %>
  		<%end%>	
  			
  		<% if @hardware_model.hardware_type.sparam3 %>
    		<%=f.label :sparam3, @hardware_model.hardware_type.sparam3 %>
  			<%=f.text_field :sparam3, class: 'form-control' %>
  		<%end%>
  			
  		<% if @hardware_model.hardware_type.iparam1 %>
    		<%=f.label :iparam1, @hardware_model.hardware_type.iparam1 %>
  			<%=f.text_field :iparam1, class: 'form-control' %>
  		<%end%>
  			
  		<% if @hardware_model.hardware_type.iparam2 %>
    			<%=f.label :iparam2, @hardware_model.hardware_type.iparam2 %>
  				<%=f.text_field :iparam2, class: 'form-control' %>
  			<%end%>	
  			
  			<% if @hardware_model.hardware_type.iparam3 %>
    			<%=f.label :iparam3, @hardware_model.hardware_type.iparam3 %>
  				<%=f.text_field :iparam3, class: 'form-control' %>
  			<%end%>
  		
		</div>
		<div class="col-md-12">
			<%=f.submit "Сохранить", class: "btn btn-primary pull-right"%>
		</div>
	<%end%>
</div>

app/views/hardware_models/_model_params.html.erb
<% if model_params.hardware_type.sparam1 %>
 	 <p><b><%= model_params.hardware_type.sparam1 %>: </b><%= model_params.sparam1 %></p>
<% end %>
<% if model_params.hardware_type.sparam2 %>
    <p><b><%= model_params.hardware_type.sparam2 %>: </b><%= model_params.sparam2 %></p>
<% end %>
<% if model_params.hardware_type.sparam3 %>
    <p><b><%= model_params.hardware_type.sparam3 %>: </b><%= model_params.sparam3 %></p>
<% end %>
<% if model_params.hardware_type.iparam1 %>
    <p><b><%= model_params.hardware_type.iparam1 %>: </b><%= model_params.iparam1 %></p>
<% end %>
<% if model_params.hardware_type.iparam2 %>
	<p><b><%= model_params.hardware_type.iparam2 %>: </b><%= model_params.iparam2 %></p>
<% end %>
<% if model_params.hardware_type.iparam3 %>
	<p><b><%= model_params.hardware_type.iparam3 %>: </b><%= model_params.iparam3 %></p>
<% end %>

app/views/hardware_models/edit.html.erb
<% provide(:title, 'Редактировать модель') %>


<%=render 'form'%>

app/views/hardware_models/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Модели оборудования</h3>
  </div>
  <div class="panel-body">
  	<table class="table table-striped">
			<thead>
				<tr>
       		<th>Модель</th>
       		<th>ID модели</th>
       		<th>Тип</th>
       		<th>Количество</th>
    		</tr>
			</thead>
			<tbody>
				<% @hardware_models.order(:hardware_type_id, :name).each do |hmodel| %>
 	   			<tr>
       			<td><%= link_to hmodel.name, hmodel %></td>
      			<td><%= hmodel.modelNo %> </td>
       			<td><%= hmodel.hardware_type.name %> </td>
       			<td><%= hmodel.hardwares.count %> </td>
    			</tr>
				<% end %>
			</tbody>
		<table>
  </div>
</div>

app/views/hardware_models/new.html.erb
<% provide(:title, 'Новая модель') %>


<%=render 'form'%>

app/views/hardware_models/show.html.erb
<% provide(:title, @hardware_model.name) %>

	

				
			<div class="panel panel-default">
  			<div class="panel-heading">
    			<h3 class="panel-title"><b>Тип: </b><%=@hardware_model.hardware_type.name%> <b>Модель: </b><%= @hardware_model.name %></h3>
    			    			
    			
  			</div>
  			<div class="panel-body">
  				<p><b>Имя:</b> <%= @hardware_model.name %></p>
  				<p><b>ID модели:</b> <%= @hardware_model.modelNo %></p>
  				<b>Комментарий:</b>
  				<pre><%=@hardware_model.comment%></pre>
  				<br>
  			     <%= render partial: "model_params", object: @hardware_model %>
  			     
  			<% if (current_user.admin?) %>
  				<div class="btn-group pull-right">
						<%=link_to "Редактировать", edit_hardware_model_path(@hardware_model), class: "btn btn-default"   %>
					</div>  			
  			<% end %>
				
			</div>
			<div class="panel panel-default">
  			<div class="panel-heading">
    			<h3 class="panel-title">Оборудование модели</h3>
    		</div>
  			<div class="panel-body">
  				<%= render partial: "shared/show_hardwares", locals: {hardwares: @hardware_model.hardwares, show_model: false, show_number: true} %>
					
					<% if (current_user.admin?) %>
						<div class="btn-group pull-right">
							<%=link_to "Добавить", new_hardware_model_hardware_path(@hardware_model), class: "btn btn-default"   %>
						</div>	
					<% end %>
				</div>
			</div>
			
			<section>
				
			</section>
			