config/routes.rb
RsvuPortal::Application.routes.draw do
  

  get 'hardware_models/index'

  get 'hardware_models/show'

  get 'hardware_models/create'

  get 'hardware_models/update'

  get 'hardware_types/index'

  get 'hardware_types/show'

  get 'hardware_types/create'

  get 'hardware_types/update'

  get "hardware_reservations/new"
  get "hardware_reservations/index"
  get "hardware_reservations/create"
  get "hardwares/new"
  get "hardwares/index"
  get "search_hardwares", to: "hardwares#search"
  get "search_vms", to: "vms#search"
  
  get "show_reservable", to: "hardwares#show_reservable"
  get "show_reservable", to: "vms#archive"
  

  resources :hardware_models, only: [:show, :edit, :destroy, :update]
	
	resources :software_types
	resources :licenses
	resources :ip_addresses
	resources :archives
	
  resources :hardware_types do
    resources :hardware_models, only: [:new, :create]
  end
    
  resources :hardware_models do 
    resources :hardwares, only: [:new, :create]
  end
  
  resources :group_relations, only: [:create]
  resources :users
  resources :groups do
    get "search_hardwares", to: "hardwares#search"
    resources :group_relations, only: [:create]
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :hardwares
  resources :events
	resources :reservations, only: [:destroy]
	resources :user_messages, only: [:destroy, :edit, :update]
  
  
  
  resources :vmhosts, only: [:index, :show]
  
  resources :vmresourcepools, only: [:show, :edit, :update]
  
  resources :vmhosts do
  	
  	resources :vms
  end
  
  resources :vms do
  	member do
    	get 'archive'
  	end
  	resources :reservations
  	resources :user_messages
  end
  
  resources :hardwares do
  	resources :reservations
  	resources :group_relations, only: [:new, :create]
    resources :devices
  	resources :softwares
  	resources :user_messages
  end
  
  root 'static_pages#home'
  match '/signup',		to: 'users#new',						via: 'get'
  match '/help',			to: 'static_pages#help',	via: 'get'
  match '/about',			to: 'static_pages#about',	via: 'get'
  match '/contact',		to: 'static_pages#contact',	via: 'get'
  match '/signin',		to: 'sessions#new',		via: 'get'
  match '/signout',		to:	'sessions#destroy',		via: 'delete'
  
 
  

end

app/models/vmresourcepool.rb
class Vmresourcepool < ActiveRecord::Base
  belongs_to :vmhost
  has_many :vms
  has_many :child_vmresourcepool, foreign_key: :parent_id, class_name: "Vmresourcepool"
	belongs_to :parent_vmresourcepool, foreign_key: :parent_id, class_name: "Vmresourcepool"
	belongs_to :creator, foreign_key: :creator_id, class_name: "User"
  
  def get_activity
		if (valid_to)
			return valid_to.to_s+" ("+creator.get_shortname+")"
		else
			return "Не используется"
		end
	end

	def get_vm_count
		vm_count = 0
		
		child_vmresourcepool.each do |rpool|
			vm_count = vm_count + rpool.get_vm_count
		end
		
		vm_count = vm_count + vms.count
		return vm_count
	end

	def get_active_vm_count
		vm_count = 0
		
		child_vmresourcepool.each do |rpool|
			vm_count = vm_count + rpool.get_active_vm_count
		end
		
		vm_count = vm_count + vms.where("state=1").count
		return vm_count
	end

  
  def Vmresourcepool.status_to_s(_Status)
		case _Status
			when 1
				return "success"
    	when 2
				return "warning"
			when 3
				return "danger"
			else
				return "default"
		end
	end		
end

app/controllers/vmresourcepools_controller.rb
class VmresourcepoolsController < ApplicationController
	def edit
		@vmresourcepool = Vmresourcepool.find(params[:id])
	end
	
	def show
		@vmresourcepool = Vmresourcepool.find(params[:id])
	end
	
	def update
		
		@vmresourcepool = Vmresourcepool.find(params[:id])
		
		@vmresourcepool.creator_id = current_user

		if @vmresourcepool.update_attributes(vmresourcepool_params)
			
			redirect_to @vmresourcepool.vmhost
		else
			render 'edit'
		end
	end
	
	private
		def vmresourcepool_params
			params.require(:vmresourcepool).permit(:valid_to, :creator_id)
		end
end

app/helpers/vmresourcepools_helper.rb
module VmresourcepoolsHelper
end

app/views/vmresourcepools/edit.html.erb
<% provide(:title, 'Пул ресурсов') %>

<div class="container">




	<div class="panel panel-info">
 		<div class="panel-heading">Указать предполагаемое окнчание использования</div>
  	<div class="panel-body">
  		<%= form_for [@vmresourcepool] do |f| %>
  			<div class="form-group">
  			 	
  			 	  			 	
  			 	<%=f.collection_select(:creator_id,User.all, :id,:get_fullname) %>	
  				
  				
  				<%=f.label :valid_to,"Срок окончания" %>
		  	  
		  	  <%= f.date_field :valid_to, class: "form-control"%>		  	
		  	   				
  				</div>
  				
				
				
				
				
  				
      		<div><%= f.submit "Сохранить", class: "btn btn-primary vert-align" %></div>
      	</div>
      	
			<% end %>
		</div>
  </div>
</div>



app/views/vmresourcepools/show.html.erb
<% provide(:title, "Пул ресурсов") %>

<h1>Пул ресурсов</h1>
<div class="row">
	<section>
			<div class="panel panel-default">
  			<div class="panel-heading">
  				<%= @vmresourcepool.name %>
  			</div>
  			
  			<div class="panel-body">
    			<div class="row">
    				<div class="col-lg-6">
  						
  						<p><b>Время создания:</b> <%=@vmresourcepool.created_at%></p>
  						  						
  						<p><b>Используется до:</b> <%=@vmresourcepool.valid_to%></p>
 							
 							
 						</div>
  					
  					<div class="col-lg-6">
  						<p><b>Время изменения:</b> <%=@vmresourcepool.updated_at%></p>
  						<% if(@vmresourcepool.creator)%>
  							<p><b>Ответственный:</b> <%=@vmresourcepool.creator.get_shortname%></p>
  						<%end%>
  					</div>
  					<div class="col-lg-12">
  						<% if (current_user.admin? || @vmresourcepool.creator.nil? || @vmresourcepool.creator==current_user ) %>
								<%=link_to "Редактировать",  edit_vmresourcepool_path(@vmresourcepool), class: "btn btn-default pull-right"%>
  						<%end%>
  					</div>
  				</div>
  				
  			
  				
  			</div>
  		</div>
		
  			<%=link_to "К хосту",  vmhost_path(@vmresourcepool.vmhost), class: "btn btn-default" %>
  			<%=link_to "Назад",  request.referrer, class: "btn btn-default" %>
			
		</section>
</div>