config/routes.rb
RsvuPortal::Application.routes.draw do
  

  get 'hardware_models/index'

  get 'hardware_models/show'

  get 'hardware_models/create'

  get 'hardware_models/update'

  get 'hardware_types/index'

  get 'hardware_types/show'

  get 'hardware_types/create'

  get 'hardware_types/update'

  get "hardware_reservations/new"
  get "hardware_reservations/index"
  get "hardware_reservations/create"
  get "hardwares/new"
  get "hardwares/index"
  get "search_hardwares", to: "hardwares#search"
  get "search_vms", to: "vms#search"
  
  get "show_reservable", to: "hardwares#show_reservable"
  get "show_reservable", to: "vms#archive"
  

  resources :hardware_models, only: [:show, :edit, :destroy, :update]
	
	resources :software_types
	resources :licenses
	resources :ip_addresses
	resources :archives
	
  resources :hardware_types do
    resources :hardware_models, only: [:new, :create]
  end
    
  resources :hardware_models do 
    resources :hardwares, only: [:new, :create]
  end
  
  resources :group_relations, only: [:create]
  resources :users
  resources :groups do
    get "search_hardwares", to: "hardwares#search"
    resources :group_relations, only: [:create]
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :hardwares
  resources :events
	resources :reservations, only: [:destroy]
	resources :user_messages, only: [:destroy, :edit, :update]
  
  
  
  resources :vmhosts, only: [:index, :show]
  
  resources :vmresourcepools, only: [:show, :edit, :update]
  
  resources :vmhosts do
  	
  	resources :vms
  end
  
  resources :vms do
  	member do
    	get 'archive'
  	end
  	resources :reservations
  	resources :user_messages
  end
  
  resources :hardwares do
  	resources :reservations
  	resources :group_relations, only: [:new, :create]
    resources :devices
  	resources :softwares
  	resources :user_messages
  end
  
  root 'static_pages#home'
  match '/signup',		to: 'users#new',						via: 'get'
  match '/help',			to: 'static_pages#help',	via: 'get'
  match '/about',			to: 'static_pages#about',	via: 'get'
  match '/contact',		to: 'static_pages#contact',	via: 'get'
  match '/signin',		to: 'sessions#new',		via: 'get'
  match '/signout',		to:	'sessions#destroy',		via: 'delete'
  
 
  

end

app/controllers/software_types_controller.rb
class SoftwareTypesController < ApplicationController
	def new
		@software_type = SoftwareType.new

	end
	

	def show
		@software_type = SoftwareType.find(params[:id])
	end
	
	def index
		@software_types =  SoftwareType.all
	end
	
	def destroy
		SoftwareType.find(params[:id]).destroy
		redirect_to software_types_path
		
	end
	
	def edit
		@software_type = SoftwareType.find(params[:id])
	end
	
	def update
		
		@software_type = SoftwareType.find(params[:id])

		if @software_type.update_attributes(software_type_params)
			redirect_to @software_type
		else
			render 'edit'
		end
	end
	
	
	def create
		
		@software_type = SoftwareType.new(software_type_params)
		
				
		if @software_type.save
			redirect_to software_types_path
		else
			
			render 'new'
		end
	end
	
	private
		def software_type_params
			params.require(:software_type).permit(:name,:comment, :sparam1, :sparam2, :sparam3, :iparam1, :iparam2, :iparam3, :type, :vendor_id, :commercial, :version)
		end



end

app/helpers/software_types_helper.rb
module SoftwareTypesHelper
end

app/views/software_types/_form.html.erb
<div class="row">
	<%=form_for( @software_type, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="col-md-6">
			
			<%=f.label :vendor_id,"Вендор" %>
		  <%=f.select(:vendor_id,Vendor.all().pluck('name','id'))%>
			
			<%=f.label :name, "Название" %>
			<%=f.text_field :name, class: 'form-control' %>

			<%=f.label :version, "Версия" %>
			<%=f.text_field :version, class: 'form-control' %>
			
			<%= f.label(:commercial, "Коммерческое") %>
			<%= f.check_box(:commercial) %>
			
			
						
			<%=f.label :comment,"Описание" %>
			<%=f.text_area :comment,  size: "60x12" %>
			
		
			
						
		</div>	
		<div class="col-md-6">
			<%=f.label :sparam1, "Текстовый параметр 1" %>
			<%=f.text_field :sparam1, class: 'form-control' %>
			
			<%=f.label :sparam2, "Текстовый параметр 2" %>
			<%=f.text_field :sparam2, class: 'form-control' %>
			
			<%=f.label :sparam3, "Текстовый параметр 3" %>
			<%=f.text_field :sparam3, class: 'form-control' %>
			
			<%=f.label :iparam1, "Числовой параметр 1" %>
			<%=f.text_field :iparam1, class: 'form-control' %>
			
			<%=f.label :iparam2, "Числовой параметр 2" %>
			<%=f.text_field :iparam2, class: 'form-control' %>
			
			<%=f.label :iparam3, "Числовой параметр 3" %>
			<%=f.text_field :iparam3, class: 'form-control' %>
		</div>
		<div class="col-md-12">
			<%=f.submit "Сохранить", class: "btn btn-primary pull-right"%>
		</div>
	<%end%>
</div>



app/views/software_types/edit.html.erb
<% provide(:title, 'Группы') %>
<h1>Редактировать ПО</h1>

<%=render 'form'%>

app/views/software_types/index.html.erb
<section>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Программное обеспечение</h3>
  </div>
  <div class="panel-body">
  	<table class="table table-striped">	
  		<thead>
  			<tr>
  				<th>Вендор</th>
  				<th>Название</th>
  				<th>Версия</th>
  				<th>Установок</th>
  			</tr>
  		</thead>
  		<tbody>
  			<% @software_types.each do |s| %>
  				<tr>
  					<td><%=s.vendor.name%></td>
  					<td><%=link_to s.name, software_type_path(s)%></td>
  					<td><%=s.version%></td>
  					<td><%=s.softwares.count%></td>
  				</tr>
  			<% end %>
  		</tbody>
  	</table>
  	
  	
		
  </div>
</div>


</section>


<div class="btn-group pull-right">
	<%=link_to "Добавить", new_software_type_path, class: "btn btn-default"   %>
</div>

app/views/software_types/new.html.erb
<% provide(:title, 'Новое ПО') %>


<%=render 'form'%>

app/views/software_types/show.html.erb
<section>
<div class="panel panel-default">
	<div class="panel-heading">
  	<h3 class="panel-title"><b>ПО:</b> <%= @software_type.name %></h3>
  </div>
  <div class="panel-body">
  	<div class="row">
  		<div class="col-md-6">
  			<p><b>Вендор: </b><%=@software_type.vendor.name%></p>
  			<p><b>Название: </b><%=@software_type.name%></p>
  			<p><b>Версия: </b><%=@software_type.version%></p>
  			<% if @software_type.commercial %>
  				<p><b>Тип лицензии: </b>Коммерческая</p>
  			<% else %>
  				<p><b>Тип лицензии: </b>Свободная</p
  			<% end %>
  		</div>
  		<div class="col-md-6">
  			<p><b>Характерные параметры:</b></p>
  			
  			<% if @software_type.sparam1 %>
  				<p><%= @software_type.sparam1 %></p>
  			<% end %>
  			<% if @software_type.sparam2 %>
  				<p><%= @software_type.sparam2 %></p>
  			<% end %>
  			<% if @software_type.sparam3 %>
  				<p><%= @software_type.sparam3 %></p>
  			<% end %>
  			<% if @software_type.iparam1 %>
  				<p><%= @software_type.iparam1 %></p>
  			<% end %>
  			<% if @software_type.iparam2 %>
  				<p><%= @software_type.iparam2 %></p>
  			<% end %>
  			<% if @software_type.iparam3 %>
  				<p><%= @software_type.iparam3 %></p>
  			<% end %>
			</div>  	
  		<div class="col-md-12">
  			<p><b>Описание:</b></p>
  			<pre><%=@software_type.comment%></pre>
  		</div>
  	</div>
  	 	
  	
  		<div class="btn-group pull-right">
				<% if (current_user.admin?) %>
					<%=link_to "Редактировать", edit_software_type_path(@software_type), class: "btn btn-default"   %>
					<%= link_to "Удалить",software_type_path(@software_type), class: "btn btn-default", method: :delete, data: {confirm: "Вы уверены?"} %>
  			<% end %>
  			<%=link_to "Назад", software_types_path, class: "btn btn-default"   %>
  		</div>
  	
  	
  </div>
 </div>
  
<% if @software_type.softwares.count > 0 %>
	<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Инсталяции</h3>
    </div>
    <div class="panel-body">
    	<%= render partial: "softwares/show_softwares", object: @software_type.softwares %>
    </div>
  </div>
<% end %>

</section>